agenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

# para o django (em desenvolvimento) servir as páginas estáticas
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from . import views
app_name = 'contact'

urlpatterns = [
    # CRUD
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),  # delete
    path('contact/<int:contact_id>/update/', views.update, name='update'),  # update
    path('contact/<int:contact_id>/', views.contact, name='contact'),  # read
    path('contact/create/', views.create, name='create'),  # create
    # busca
    path('search/', views.search, name='search'),
    # home
    path('', views.index, name='index'),

    # user
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),

]

contact/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
# Create your models here.
"""
# no model Contact
id: primary key (automatico), fisrt_name: str, last_name: str, phone: str, email: email, crete_date: date, description: text (> 255 caracteres),
category: foreign key, show: boolean,, picture: imagem
owner: foreign key
"""
# blank -> torna o campo opcional


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=15)

    def __str__(self) -> str:
        return f"{str(self.name)}"


class Contact(models.Model):
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=85)
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    created_date = models.DateTimeField(default=now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to="pictures/%Y/%m/%d")
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )

    def __str__(self) -> str:
        return f"{str(self.first_name)} {str(self.last_name)}"

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from contact.models import Contact
from django.contrib.auth import password_validation


class ContactForms(forms.ModelForm):

    # campos presentes no model
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'digite seu nome aqui',
            }
        ),
        label='Nome',
        help_text='apenas o primeiro nome',
        required=True,
        max_length=15,
        min_length=3,
        strip=True
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'digite o restante do seu nome aqui',
            }
        ),
        label='Sobrenome: ',
        help_text='o restante do seu nome',
        required=True,
        max_length=50,
        min_length=3,
        strip=True
    )
    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': '(+55) 21 98888-7777',
            }
        ),
        label='telefone: ',
        help_text='com o ddd e ddi',
        required=True,
        max_length=13,
        min_length=11,
        strip=True
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'youremail_here@email.com',
            }
        ),
        label='Email: ',
        help_text='seu email',
        required=True,
        max_length=50,
        min_length=3,
    )
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
              'accept': 'image/*',
            }
        ),
        label='Imagem '
    )

    class Meta:
        model = Contact
        fields = (
            'first_name',
            'last_name',
            'phone',
            'email',
            'description',
            'category',
            'picture'
        )

    def clean(self):
        # cleaned_data = self.cleaned_data
        # print(cleaned_data)
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError(
                'O segundo nome não pode ser consoante o primeiro nome',
                code='invalid'
            )
            self.add_error(
                'last_name',
                msg
            )
        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        validator_name = True
        for letter in str(first_name):
            if letter.isnumeric():
                validator_name = False
                break

        if not validator_name:
            self.add_error(
                'first_name',
                ValidationError(
                    'Não pode conter numeros',
                    code='invalid'
                )
            )

        return first_name


class RegisterForm(UserCreationForm):

    first_name = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'placeholder': 'seu nome',
            }
        ),
        required=True,
        min_length=3,
        max_length=15,
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'seu sobrenome',
            }
        ),
        required=True,
        min_length=3,
        max_length=100,
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'email@subdominio.com',
            }
        ),
        required=True,
    )

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError(
                    'Esse e-mail já existe',
                    code='invalid'
                )
            )

        return email


class RegisterUpdateForm(forms.ModelForm):

    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text="Required.",
        error_messages={
            "min_length": "Please, add more than 2 letters"
        }
    )

    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text="Required.",
        error_messages={
            "min_length": "Please, add more than 2 letters"
        }
    )
    password1 = forms.CharField(
        label="Password1",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False
    )
    password2 = forms.CharField(
        label="Password2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text="Use the same password as before",
        required=False
    )

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user

    def clean_email(self):

        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError("Já existe esse email", code='invalid')
                )
        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as error:
                self.add_error(
                    'password1',
                    ValidationError(
                        error
                    )
                )

        return password1

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 != password1:
            self.add_error(
                'password2',
                ValidationError(
                    'as senhas são diferentes'
                )
            )

        return super().clean()

contact/views/contact_forms.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from contact.forms import ContactForms
from django.urls import reverse
from contact.models import Contact


@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')
    if request.method == 'POST':

        form = ContactForms(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
            'mode': 'Create'
        }
        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            return redirect(
                f'contact:update',
                contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context=context,
        )

    context = {
        'form': ContactForms(),
        'form_action': form_action,
        'mode': 'Create'
    }
    return render(request,
                  'contact/create.html',
                  context=context,
                  )


@login_required(login_url='contact:login')
def update(request, contact_id):
    form_action = reverse('contact:update', args=(contact_id,))
    contact = get_object_or_404(
        Contact,
        pk=contact_id,
        show=True,
        owner=request.user
    )
    if request.method == 'POST':

        form = ContactForms(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
            "mode": "Update"
        }
        if form.is_valid():
            contact = form.save()
            return redirect(
                f'contact:update',
                contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context=context,
        )

    context = {
        'form': ContactForms(instance=contact),
        'form_action': form_action,
        "mode": 'Update'
    }
    return render(
        request,
        'contact/create.html',
        context=context,
    )


@login_required(login_url='contact:login')
def delete(request, contact_id):
    # form_action = reverse('contact:update', args=(contact_id,))
    contact = get_object_or_404(
        Contact,
        pk=contact_id,
        show=True,
        owner=request.user
    )
    confirmation = request.POST.get('confirmation', 'no')
    if confirmation == 'yes':
        contact.delete()
        return redirect("contact:index")

    return render(
        request,
        "contact/contact.html",
        {
            "contact": contact,
            "confirmation": confirmation,
        }
    )

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import Contact
from django.core.paginator import Paginator
from django.db.models import Q
# from django.http import Http404


# Create your views here.
def contact(request, contact_id):
    # single_contact = Contact.objects.filter(pk=contact_id, show=True).first()
    single_contact = get_object_or_404(
        Contact,
        pk=contact_id,
        show=True
    )

    # if single_contact is None:
    #     raise Http404()

    context = {
        'contact': single_contact,
        'site_title': f"{single_contact.first_name} {single_contact.last_name}: ",
    }
    return render(request,
                  'contact/contact.html', context=context)


# ATENÇÃO: essa view vai no action do form
def search(request):
    # "querry" é o name do form
    search_value = request.GET.get('querry', '').strip()

    if not search_value:
        return redirect("contact:index")

    # nome_do_campo__<método>
    contacts = Contact.objects \
        .filter(show=True) \
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value)
        ) \
        .order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'search_value': search_value,
    }

    return render(request,
                  'contact/index.html', context=context)


def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }
    return render(request,
                  'contact/index.html',
                  context=context,
                  )

contact/views/user_forms.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.forms import AuthenticationForm
from contact.forms import RegisterForm, RegisterUpdateForm
from django.contrib.auth.decorators import login_required


def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                'Usuário registrado com sucesso!'
            )
            return redirect('contact:login')
        else:
            messages.error(
                request,
                'O formulário possui algum um erro!'
            )

    return render(
        request,
        'contact/register.html',
        {
            'form': form,
            'mode': 'Register',
        }
    )


def login_view(request):

    form = AuthenticationForm(request)
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            print(f'login realizado: {user}')
            messages.success(request, f'Bem vindo, {user}')
            return redirect(
                        "contact:index"
                    )
        messages.error(request, 'Login inválido')

    return render(
        request,
        'contact/login.html',
        {
            'form': form,
            'mode': 'Login',
        }
    )


@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    print('logout realizado')
    return redirect(
        'contact:login'
    )


@login_required(login_url='contact:login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':

        return render(
            request,
            'contact/register.html',
            {
                'form': form,
                'mode': 'User Update',
            }
        )

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'contact/register.html',
            {
                'form': form,
                'mode': 'User Update',

            }
        )
    form.save()
    messages.success(request, f'Atualizado com sucesso.')
    return redirect('contact:user_update')

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{contact.last_name}}
        </h1>
        <p><b>ID: </b>{{contact.id}}</p>
        <p><b>Phone: </b>{{contact.phone}}</p>
        <p><b>E-mail: </b>{{contact.email}}</p>
        <p><b>Created date: </b>{{contact.created_name}}</p>
        <p><b>Category: </b>{{contact.category.name}}</p>
        <p><b>Description: </b>{{contact.description}}</p>
        {% if contact.picture %}
        <p>
            <img src="{{contact.picture.url}}" alt="{{contact.first_name}}{{contact.last_name}}"></img>
        </p>
        {% endif %}
        {% if contact.owner == user %}
        <div class="contact-links">
            <a class="btn btn-link" href="{% url "contact:update" contact.id %}">Update</a>
            <form action="{% url "contact:delete" contact.id %}" method='POST'>
                {% csrf_token %}
                {% if confirmation == 'no' %}
                    <input type="hidden" name='confirmation' value='yes'></input>
                    <button class="btn btn-link btn-delete" type="">Confirma?</button>
                {% else %}
                    <button class="btn btn-link btn-delete" type="submit">Delete</button>
                {% endif %}
            </form>
        </div>
        {% endif %}
    </div>
    
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}
{% block content %}
<h1>{{mode}}</h1>
<div class="form-wrapper">

  <h2>Contact</h2>

  <form 
    action="{{form_action}}"
    method="POST"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <div class="form-content">
      {% for field in form %}
        <div class="form-group">
          <label for="{{field.id_for_label}}">{{field.label}}:</label>
          {{field}}
          {{field.errors}}
          {% if field.help_text %}
            <p class="help-text">
              {{field.help_text}}
            </p>
          {% endif %}
          
        </div>
      {% endfor %}

      {% if form.non_field_errors %}
        <div class='form.content'>
          <div class='form-group'>
            <div class='message error'>
              {{form.non_field_errors}}
            </div>    
          </div>
        </div>
      {% endif %}

    </div>

    

    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>

  </form>
</div>
{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}
{% block content %}
    {% if page_obj %}
        <div class = 'responsive-table'>
            <table class="contacts-table">
                <caption class='table-caption'>
                    Contacts
                </caption>
                <thead>
                    <tr class = "table-row table-row-header">
                        <th class="table-header">ID</th>
                        <th class="table-header">First name</th>
                        <th class="table-header">Last name</th>
                        <th class="table-header">Phone</th>
                        <th class="table-header">E-mail</th>
                    <tr>
                </thead>
                <tbody class="">
                    {% for contact in page_obj %}
                        <tr class = "table-row">
                            <td class="table-cel">
                                <a class='table-link' 
                                href="{% url 'contact:contact' contact.id %}">
                                    {{contact.id}}
                                </a>
                            </td>
                            <td class="table-cel">
                                {{contact.first_name}}
                            </td>
                            <td class="table-cel">
                                {{contact.last_name}}
                            </td>
                            <td class="table-cel">
                                {{contact.phone}}
                            </td>
                            <td class="table-cel">
                                {{contact.email}}
                            </td>
                        <tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum contato encontrado!!!
        </h1>
    </div>
    {% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends "global/base.html" %}
{% block content %}
<div class="form-wrapper">

    {% if user.is_authenticated %}
        <h2 class="sub-title">Olá, <span class="sub-header-link">{{user}}</span></h2>
        
        <div class="single-contact">
            <p><b>usuário:</b> {{user.username}}</p>
            <p><b>email:</b> {{user.email}}</p>
            <p><b>primeiro nome:</b> {{user.first_name}}</p>
            <p><b>segundo nome:</b> {{user.last_name}}</p>
        </div>
        <p>
            <a href="{% url "contact:user_update" %}" class="btn btn-link">Alterar dados</a>
        </p>
    {% else %}
        <h2>{{mode}}</h2>
        {% include "contact/partials/_user-forms.html" %}
    {% endif %}
  
</div>
{% endblock content %}

contact/templates/contact/register.html
{% extends "global/base.html" %}
{% block content %}
<div class="form-wrapper">

  <h2>{{mode}}</h2>
  {% include "contact/partials/_user-forms.html" %}
  
</div>
{% endblock content %}